### ISSUE TITLE
Error In Cross Copy

### ISSUE THREAD

**Issue by Prashast07** [pbudzon/aws-maintenance#12]
When I am running the test function for aurora I am getting below error. Until now it was working fine but now i am seeing this error
An error occurred (SnapshotQuotaExceeded) when calling the CopyDBClusterSnapshot operation: Cannot create more than 100 manual snapshots: SnapshotQuotaExceededFault
Traceback (most recent call last):
 File “/var/task/backup-rds.py”, line 259, in lambda_handler
   copy_latest_snapshot(account_id, cluster, True)
 File “/var/task/backup-rds.py”, line 172, in copy_latest_snapshot
   SourceRegion=SOURCE_REGION
 File “/var/runtime/botocore/client.py”, line 314, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File “/var/runtime/botocore/client.py”, line 612, in _make_api_call
   raise error_class(parsed_response, operation_name)
botocore.errorfactory.SnapshotQuotaExceededFault: An error occurred (SnapshotQuotaExceeded) when calling the CopyDBClusterSnapshot operation: Cannot create more than 100 manual snapshots

**Comment by Prashast07** [comment]
Done

**Comment by pbudzon** [comment]
@Prashast07 I'm guessing you had too many snapshots in place after modifying the retention policy? If you could share if that's the case or there was another problem, for anyone else who may encounter this.

**Comment by Prashast07** [comment]
We cannot have more than 100 snapshots in one region. So if i manually delete one of the snapshot the  cross region copy happened as expected.
