### ISSUE TITLE
Resource import error

### ISSUE THREAD

**Issue by crino85** [pbudzon/aws-maintenance#16]
Hello,

When I try to create the CloudFormation stack from the json template I got this error:

"The following resource types are not supported for resource import: AWS::Lambda::Permission,AWS::RDS::EventSubscription,AWS::Lambda::Permission"

Can you advice?

Thanks,
Carlos

**Comment by pbudzon** [comment]
Hi @crino85 

Are you trying to use the "import resources" button when creating the stack? As per the message, that's not supported for Lambda-related resources. You need to choose "Create stack" -> "With new resources (standard)" button, to create the stack from scratch.

<img width="388" alt="Screenshot 2020-04-06 at 13 52 02" src="https://user-images.githubusercontent.com/1087886/78555746-f6475780-780d-11ea-8206-9ac1c77b0601.png">

**Comment by crino85** [comment]
Great thanks!
