### ISSUE TITLE
Cross Region RDS Backup Copy CFN Not working

### ISSUE THREAD

**Issue by vennemp** [pbudzon/aws-maintenance#18]
I cloned your git repository to my local machine, uploaded the zipped python for RDS cross region backup copy to an s3 bucket.  However when I upload the CFN template into the console it fails.  Are you sure the provided template is valid?

![image](https://user-images.githubusercontent.com/26049891/79889482-13faec00-83cc-11ea-99ee-63c392badfab.png)

**Comment by pbudzon** [comment]
Hi @vennemp 

From the screenshot, there doesn't seem to be an issue with the template, but during the uploading - did you try uploading it again? Or restarting your browser? If there is an issue with the template, there tends to be a very different error message - definitely nothing about "failed upload".

**Comment by vennemp** [comment]
Yeah I've multiple browsers, incognito, however it works for my coworker so there is definitely something screwy with my workstation.  You can close this.  Thank you for the fast response!

**Comment by vennemp** [comment]
Btw this works great after we got issue sorted out.  Thanks for creating a professional solution to this problem!
