### ISSUE TITLE
Lambda function is triggered but fails

### ISSUE THREAD

**Issue by fsantarelli** [pbudzon/aws-maintenance#3]
Hi @pbudzon - and apologies if this is not the right place to discuss this error.

I've used your amazing code to deploy a CloudFormation stack to copy RDS snapshots from one region to another, following the readme instructions. First I tried to deploy it on the destination region and it failed, but then it was successfully deployed in the snapshot source region - the one that has the RDS instance that is generating the snapshots.

But the Lambda Function is failing to copy the snapshot. I don't know if it is related to the fact that our snapshots are encrypted or something else, but the log suggests that it is failing to identify that there's no copy of the snapshot in the destination region, like if the snapshot was already copied, and then the function quits without running the copy itself.

![image](https://user-images.githubusercontent.com/20211639/35094793-4b35551a-fc3e-11e7-8d8c-d08a1d839cb2.png)

Can you advise on this please? Or is there a restriction on encrypted snapshots?

Many thanks.

**Comment by jtotham** [comment]
Perfect timing, I was trying to get this too work last night and am having exactly the same issue.

```15:12:16
Latest snapshot found: 'rds:dr4r6hb7p917va-2018-01-18-15-05' from 2018-01-18 15:06:09.565000+00:00
Latest snapshot found: 'rds:dr4r6hb7p917va-2018-01-18-15-05' from 2018-01-18 15:06:09.565000+00:00

15:12:16
Checking if 'dr4r6hb7p917va-us-east-1-rds:dr4r6hb7p917va-2018-01-18-15-05' already exists in target region
Checking if 'dr4r6hb7p917va-us-east-1-rds:dr4r6hb7p917va-2018-01-18-15-05' already exists in target region

15:12:16
dr4r6hb7p917va-us-east-1-rds:dr4r6hb7p917va-2018-01-18-15-05 is already copied to us-west-2
dr4r6hb7p917va-us-east-1-rds:dr4r6hb7p917va-2018-01-18-15-05 is already copied to us-west-2

15:12:17
No snapshots for database dr4r6hb7p917va found in target region: Exception Traceback (most recent call last): File "/var/task/index.py", line 101, in lambda_handler remove_old_snapshots(message['Source ID']) File "/var/task/index.py", line 68, in remove_old_snapshots raise Exception("No snapshots for database {} found in target region".format(instance_name)) Exception: No snapshots for
No snapshots for database dr4r6hb7p917va found in target region: Exception
Traceback (most recent call last):
File "/var/task/index.py", line 101, in lambda_handler
remove_old_snapshots(message['Source ID'])
File "/var/task/index.py", line 68, in remove_old_snapshots
raise Exception("No snapshots for database
{}
found in target region".format(instance_name))
Exception: No snapshots for database dr4r6hb7p917va found in target region```

**Comment by jtotham** [comment]
I think the issue is where that copy_name is being built up and coming out as `dr4r6hb7p917va-us-east-1-rds:dr4r6hb7p917va-2018-01-18-15-05` this string contains a `:` which is not a valid char for the target name. 

This then means the error being returned when it tries to do the copy action does not match the exception that is looking for "DBSnapshotNotFound" and it moves on past straight to `   print("{} is already copied to {}".format(copy_name, TARGET_REGION))`

If I try and and perform the same copy in the console using the name generated I get this following error:

https://i.imgur.com/pr6jGM6.png

**Comment by pbudzon** [comment]
Hi both,

Thanks for the report. I'm looking into this now.

@fsantarelli  - you mentioned that the stack creation failed in the target region? Can you raise another issue with more details about this?

**Comment by fsantarelli** [comment]
Hi @pbudzon - thanks for your message, I can definitely raise another issue regarding the region issue.

**Comment by pbudzon** [comment]
Hi @fsantarelli @jtotham 

You were correct, the : in the naming was causing an error. I pushed a fixed code which replaces that with a hyphen, which is an allowed character. The CloudFormation template is updated, so all you should need to do now is update your stacks and it should be working.

If you want to do some manual testing in the Lambda console, an example event (replace the database name with your own, everything else is ignored):
```
{
  "Records": [
    {
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:EXAMPLE",
      "EventSource": "aws:sns",
      "Sns": {
        "Type": "Notification",
        "MessageId": "abcd",
        "TopicArn": "arn:aws:sns:eu-west-1:123456789012:topic_name",
        "Subject": "RDS Notification Message",
        "Message": "{\"Event Source\":\"db-instance\",\"Event Time\":\"2017-12-26 22:34:07.882\",\"Identifier Link\":\"https://console.aws.amazon.com/rds/home?region=eu-west-1#dbinstance:id=database_name\",\"Source ID\":\"PUT_YOUR_RDS_NAME_HERE\",\"Event ID\":\"http://docs.amazonwebservices.com/AmazonRDS/latest/UserGuide/USER_Events.html#RDS-EVENT-0002\",\"Event Message\":\"Finished DB Instance backup\"}",
        "Timestamp": "2017-12-26T22:35:19.946Z",
        "SignatureVersion": "1",
        "Signature": "xxx",
        "SigningCertURL": "xxx",
        "UnsubscribeURL": "xxx"
      }
    }
  ]
}
```

Thanks for the report!
