### ISSUE TITLE
Issue in taking snapshot

### ISSUE THREAD

**Issue by Prashast07** [pbudzon/aws-maintenance#8]
I am getting error, could you please guide. Please see the attached screenshot
<img width="1613" alt="screen shot 2018-01-24 at 4 02 05 pm" src="https://user-images.githubusercontent.com/17633798/35363712-3281d0e8-0120-11e8-977a-30c141102720.png">

**Comment by pbudzon** [comment]
Hi @Prashast07

I'm guessing this is about the KMS Key parameter. Did you provide a full ARN for the "KMS Key in target region" parameter or left the field empty?
Full guide on using the template is available in [README](https://github.com/pbudzon/aws-maintenance#guide---how-to-use-and-test).

**Comment by Prashast07** [comment]
Thanks @pbudzon , you were right. It worked after giving the full ARN
