### ISSUE TITLE
Aurora support

### ISSUE THREAD

**Issue by Prashast07** [pbudzon/aws-maintenance#9]
I have multiple instances in RDS, one with **AuroraMySQL engine** & one with MySQL engine. In my source region snapshot has been created for both but in the target region only the snapshot related to MySQL engine has been created not for the **AuroraMySQL engine**. 
As mentioned in the readme file i have left the DatabasesToUse as empty because i wanted the snapshots of all the RDS instances to be copied in the destination region.
Do i need to do something else in the code? Kindly suggest

**Comment by pbudzon** [comment]
Hi @Prashast07,

Since Aurora runs in clusters and not sole instances, it seems RDS notifications for it are different. I can't seem to find a reference to what the event is for automated snapshot for Aurora. Can you take a screenshot of Events on your Aurora cluster or run:
```
aws rds describe-events --source-identifier NAME_OF_YOUR_CLUSTER
```

The Lambda code also probably needs to be modified to use `describe_db_cluster_snapshots` instead of `describe_db_snapshots` for Aurora.

**Comment by Prashast07** [comment]
sh-3.2# aws rds describe-events --source-identifier dev-aurora --source-type db-cluster
{
    "Events": []
}
sh-3.2#

**Comment by Prashast07** [comment]
Hi @pbudzon 
Shall i try with  describe_db_cluster_snapshots in the lambda code??

**Comment by pbudzon** [comment]
Hi @Prashast07 

There's probably more adjustments needed to the code, but feel free to experiment. I'd love to merge a pull request with support for Aurora added :)

**Comment by Prashast07** [comment]
Hi @pbudzon 
rds-cross-region-backup.json which i will use to create cloud formation template will remain the same even for aurora backups

**Comment by pbudzon** [comment]
The template has not been changed yet, the support is currently in a feature branch as a work in progress (WIP) and not ready to use. I'm hoping to get it tested and merged into master later this evening!

**Comment by pbudzon** [comment]
Hi @Prashast07 
I've added the support to Aurora. Please check out the updated README on how to deploy the changes.
